use std::path::Path;

use mlx_rs::fast;
use mlx_rs::module::Module;
use mlx_rs::nn::{self, Conv1d};
use mlx_rs::ops::{concatenate_axis, indexing::IndexOp, stack_axis};
use mlx_rs::{Array, Dtype};

use crate::checkpoint::Checkpoint;
use crate::{Error, Result};

/// Number of complex STFT frequency bins.
pub const N_FREQS: i32 = 2049;
/// Number of mel-spaced frequency bands.
pub const N_BANDS: i32 = 80;
/// Internal feature width.
pub const FEATURE_DIM: i32 = 128;
const NUM_HEADS: i32 = 16;
const HEAD_DIM: i32 = FEATURE_DIM / NUM_HEADS;
const RMS_EPS: f32 = 1e-5;
const MODEL_EPS: f32 = 1e-7;

/// Exact band widths generated by the reference model for 48 kHz and 4096-point STFT.
pub const BAND_WIDTHS: [i32; N_BANDS as usize] = [
    4, 4, 4, 3, 3, 3, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 6, 7, 7, 7, 8, 8, 8, 9, 9, 9, 10, 10,
    11, 11, 12, 12, 13, 14, 14, 15, 15, 16, 17, 18, 18, 19, 20, 21, 22, 23, 24, 25, 26, 28, 29, 30,
    32, 33, 34, 36, 38, 39, 41, 43, 45, 47, 49, 51, 54, 56, 59, 62, 64, 67, 70, 74, 77, 80, 84, 88,
    92,
];

#[derive(Debug)]
struct TorchRmsNorm {
    weight: Array,
    eps_half: Array,
}

impl TorchRmsNorm {
    fn load(checkpoint: &mut Checkpoint, name: impl Into<String>, dimensions: i32) -> Result<Self> {
        Ok(Self {
            weight: checkpoint.tensor(name, &[dimensions])?,
            eps_half: Array::from_f32(RMS_EPS).as_dtype(Dtype::Float16)?,
        })
    }

    fn forward(&self, input: &Array) -> Result<Array> {
        // The reference RMSNorm intentionally computes variance and rsqrt in FP16,
        // then promotes during multiplication by the FP32 learned weight.
        let half = input.as_dtype(Dtype::Float16)?;
        let variance = half.square()?.mean_axis(-1, true)?;
        let normalized = half.multiply(variance.add(&self.eps_half)?.rsqrt()?)?;
        Ok(normalized.multiply(&self.weight)?)
    }
}

#[derive(Debug)]
struct FeatureExtractor {
    norm: TorchRmsNorm,
    projection: Conv1d,
}

impl FeatureExtractor {
    fn load(checkpoint: &mut Checkpoint, index: usize, band_width: i32) -> Result<Self> {
        let input_channels = band_width * 2 + 1;
        Ok(Self {
            norm: TorchRmsNorm::load(
                checkpoint,
                format!("feature_extractor_layers.{index}.0.weight"),
                input_channels,
            )?,
            projection: checkpoint.conv1d(
                &format!("feature_extractor_layers.{index}.1"),
                input_channels,
                FEATURE_DIM,
                1,
                true,
                0,
                1,
                1,
            )?,
        })
    }

    fn forward(&mut self, input: &Array) -> Result<Array> {
        let normalized = self.norm.forward(input)?;
        Ok(self.projection.forward(&normalized)?)
    }
}

#[derive(Debug)]
struct Roformer {
    cos_freq: Array,
    sin_freq: Array,
    input_norm: TorchRmsNorm,
    qkv: Conv1d,
    output: Conv1d,
    mlp_norm: TorchRmsNorm,
    mlp: Conv1d,
    mlp_output: Conv1d,
}

impl Roformer {
    fn load(checkpoint: &mut Checkpoint, prefix: &str) -> Result<Self> {
        Ok(Self {
            cos_freq: checkpoint.tensor(format!("{prefix}.cos_freq"), &[512, HEAD_DIM])?,
            sin_freq: checkpoint.tensor(format!("{prefix}.sin_freq"), &[512, HEAD_DIM])?,
            input_norm: TorchRmsNorm::load(
                checkpoint,
                format!("{prefix}.input_norm.weight"),
                FEATURE_DIM,
            )?,
            qkv: checkpoint.conv1d(
                &format!("{prefix}.weight"),
                FEATURE_DIM,
                FEATURE_DIM * 3,
                1,
                false,
                0,
                1,
                1,
            )?,
            output: checkpoint.conv1d(
                &format!("{prefix}.output"),
                FEATURE_DIM,
                FEATURE_DIM,
                1,
                false,
                0,
                1,
                1,
            )?,
            mlp_norm: TorchRmsNorm::load(
                checkpoint,
                format!("{prefix}.MLP.0.weight"),
                FEATURE_DIM,
            )?,
            mlp: checkpoint.conv1d(
                &format!("{prefix}.MLP.1"),
                FEATURE_DIM,
                FEATURE_DIM * 8,
                1,
                false,
                0,
                1,
                1,
            )?,
            mlp_output: checkpoint.conv1d(
                &format!("{prefix}.MLP_output"),
                FEATURE_DIM * 4,
                FEATURE_DIM,
                1,
                false,
                0,
                1,
                1,
            )?,
        })
    }

    fn apply_rotary(&self, feature: &Array, sequence_length: i32) -> Result<Array> {
        let shape = feature.shape();
        let paired = feature.reshape(&[shape[0], shape[1], sequence_length, HEAD_DIM / 2, 2])?;
        let first = paired.index((.., .., .., .., 0));
        let second = paired.index((.., .., .., .., 1));
        let reversed = stack_axis(&[second.negative()?, first], -1)?.reshape(feature.shape())?;
        let cos =
            self.cos_freq
                .index(0..sequence_length)
                .reshape(&[1, 1, sequence_length, HEAD_DIM])?;
        let sin =
            self.sin_freq
                .index(0..sequence_length)
                .reshape(&[1, 1, sequence_length, HEAD_DIM])?;
        Ok(feature.multiply(cos)?.add(reversed.multiply(sin)?)?)
    }

    fn forward(&mut self, input: &Array) -> Result<Array> {
        let batch = input.dim(0);
        let sequence_length = input.dim(1);
        let normalized = self.input_norm.forward(input)?;
        let qkv = self
            .qkv
            .forward(&normalized)?
            .reshape(&[batch, sequence_length, NUM_HEADS, HEAD_DIM * 3])?
            .transpose_axes(&[0, 2, 1, 3])?;
        let qkv = qkv.split(3, -1)?;
        let query = self.apply_rotary(&qkv[0], sequence_length)?;
        let key = self.apply_rotary(&qkv[1], sequence_length)?;
        let attended = fast::scaled_dot_product_attention(
            &query,
            &key,
            &qkv[2],
            1.0 / (HEAD_DIM as f32).sqrt(),
            None,
            None,
        )?
        .transpose_axes(&[0, 2, 1, 3])?
        .reshape(&[batch, sequence_length, FEATURE_DIM])?;
        let output = self.output.forward(&attended)?.add(input)?;

        // This preserves the reference's two SiLU applications on the gate:
        // Sequential(..., SiLU), followed by F.silu(gate) * values.
        let mlp_input = self.mlp_norm.forward(&output)?;
        let activated = nn::silu(self.mlp.forward(&mlp_input)?)?;
        let parts = activated.split(2, -1)?;
        let gated = nn::silu(&parts[0])?.multiply(&parts[1])?;
        Ok(self.mlp_output.forward(&gated)?.add(output)?)
    }
}

#[derive(Debug)]
struct ConvBlock {
    depthwise: Conv1d,
    norm: TorchRmsNorm,
    pointwise_in: Conv1d,
    pointwise_out: Conv1d,
}

impl ConvBlock {
    fn load(checkpoint: &mut Checkpoint, prefix: &str, dilation: i32) -> Result<Self> {
        Ok(Self {
            depthwise: checkpoint.conv1d(
                &format!("{prefix}.dwconv"),
                FEATURE_DIM,
                FEATURE_DIM,
                7,
                true,
                3 * dilation,
                dilation,
                FEATURE_DIM,
            )?,
            norm: TorchRmsNorm::load(checkpoint, format!("{prefix}.norm.weight"), FEATURE_DIM)?,
            pointwise_in: checkpoint.conv1d(
                &format!("{prefix}.pwconv1"),
                FEATURE_DIM,
                FEATURE_DIM * 4,
                1,
                true,
                0,
                1,
                1,
            )?,
            pointwise_out: checkpoint.conv1d(
                &format!("{prefix}.pwconv2"),
                FEATURE_DIM * 2,
                FEATURE_DIM,
                1,
                true,
                0,
                1,
                1,
            )?,
        })
    }

    fn forward(&mut self, input: &Array) -> Result<Array> {
        let depthwise = self.depthwise.forward(input)?;
        let normalized = self.norm.forward(&depthwise)?;
        let projected = self.pointwise_in.forward(&normalized)?;
        let gated = nn::glu(&projected, -1)?;
        Ok(self.pointwise_out.forward(&gated)?)
    }
}

#[derive(Debug)]
struct Icb {
    first: ConvBlock,
    dilated: ConvBlock,
    third: ConvBlock,
    gamma: Array,
}

impl Icb {
    fn load(checkpoint: &mut Checkpoint, prefix: &str, dilation: i32) -> Result<Self> {
        Ok(Self {
            first: ConvBlock::load(checkpoint, &format!("{prefix}.block1"), 1)?,
            dilated: ConvBlock::load(checkpoint, &format!("{prefix}.block2"), dilation)?,
            third: ConvBlock::load(checkpoint, &format!("{prefix}.block3"), 1)?,
            gamma: checkpoint.tensor(format!("{prefix}.gamma"), &[FEATURE_DIM])?,
        })
    }

    fn forward(&mut self, input: &Array) -> Result<Array> {
        let first = self.first.forward(input)?;
        let second = self.dilated.forward(&first)?;
        let third = self.third.forward(&second)?;
        Ok(third.multiply(&self.gamma)?.add(input)?)
    }
}

#[derive(Debug)]
struct BsNet {
    band_net: Roformer,
    sequence_net: Icb,
}

impl BsNet {
    fn load(checkpoint: &mut Checkpoint, index: usize, dilation: i32) -> Result<Self> {
        Ok(Self {
            band_net: Roformer::load(checkpoint, &format!("net.{index}.band_net"))?,
            sequence_net: Icb::load(checkpoint, &format!("net.{index}.seq_net"), dilation)?,
        })
    }

    fn forward(&mut self, input: &Array) -> Result<Array> {
        // Natural MLX layout is [batch, time, band, feature]. Band attention
        // therefore requires no transpose before flattening batch and time.
        let batch = input.dim(0);
        let frames = input.dim(1);
        let band_input = input.reshape(&[batch * frames, N_BANDS, FEATURE_DIM])?;
        let band_output =
            self.band_net
                .forward(&band_input)?
                .reshape(&[batch, frames, N_BANDS, FEATURE_DIM])?;

        let sequence_input = band_output.transpose_axes(&[0, 2, 1, 3])?.reshape(&[
            batch * N_BANDS,
            frames,
            FEATURE_DIM,
        ])?;
        Ok(self
            .sequence_net
            .forward(&sequence_input)?
            .reshape(&[batch, N_BANDS, frames, FEATURE_DIM])?
            .transpose_axes(&[0, 2, 1, 3])?)
    }
}

#[derive(Debug)]
struct OutputSynthesis {
    norm: TorchRmsNorm,
    projection_in: Conv1d,
    projection_out: Conv1d,
    band_width: i32,
}

impl OutputSynthesis {
    fn load(checkpoint: &mut Checkpoint, index: usize, band_width: i32) -> Result<Self> {
        Ok(Self {
            norm: TorchRmsNorm::load(
                checkpoint,
                format!("output_layers.{index}.0.weight"),
                FEATURE_DIM,
            )?,
            projection_in: checkpoint.conv1d(
                &format!("output_layers.{index}.1"),
                FEATURE_DIM,
                FEATURE_DIM * 2,
                1,
                true,
                0,
                1,
                1,
            )?,
            projection_out: checkpoint.conv1d(
                &format!("output_layers.{index}.3"),
                FEATURE_DIM * 2,
                band_width * 4,
                1,
                true,
                0,
                1,
                1,
            )?,
            band_width,
        })
    }

    fn forward(&mut self, input: &Array) -> Result<Array> {
        let normalized = self.norm.forward(input)?;
        let hidden = nn::silu(self.projection_in.forward(&normalized)?)?;
        let projected = self.projection_out.forward(&hidden)?;
        let gated = nn::glu(&projected, -1)?;
        Ok(gated.reshape(&[input.dim(0), input.dim(1), self.band_width, 2])?)
    }
}

/// Complete Smule Renaissance Small inference network.
#[derive(Debug)]
pub struct Renaissance {
    feature_extractors: Vec<FeatureExtractor>,
    network: Vec<BsNet>,
    output_layers: Vec<OutputSynthesis>,
}

impl Renaissance {
    /// Load the converted, MLX-layout safetensors checkpoint.
    pub fn load(path: impl AsRef<Path>) -> Result<Self> {
        let mut checkpoint = Checkpoint::load(path)?;
        let mut feature_extractors = Vec::with_capacity(N_BANDS as usize);
        let mut output_layers = Vec::with_capacity(N_BANDS as usize);
        for (index, &band_width) in BAND_WIDTHS.iter().enumerate() {
            feature_extractors.push(FeatureExtractor::load(&mut checkpoint, index, band_width)?);
            output_layers.push(OutputSynthesis::load(&mut checkpoint, index, band_width)?);
        }

        let dilations = [1, 1, 1, 2, 4, 4, 4, 4, 4];
        let mut network = Vec::with_capacity(dilations.len());
        for (index, dilation) in dilations.into_iter().enumerate() {
            network.push(BsNet::load(&mut checkpoint, index, dilation)?);
        }
        checkpoint.finish()?;

        Ok(Self {
            feature_extractors,
            network,
            output_layers,
        })
    }

    /// Run the network on `[batch, frames, 2049, real_imag]` FP32 STFT data.
    pub fn forward(&mut self, input: &Array) -> Result<Array> {
        self.forward_internal(input, None)
    }

    /// Run inference while recording major reference-model boundaries.
    ///
    /// The callback is intended for numerical validation and forces no
    /// evaluations by itself. Production inference should use [`Self::forward`].
    pub fn forward_with_trace<F>(&mut self, input: &Array, mut trace: F) -> Result<Array>
    where
        F: FnMut(&str, &Array) -> Result<()>,
    {
        self.forward_internal(input, Some(&mut trace))
    }

    fn forward_internal(
        &mut self,
        input: &Array,
        mut trace: Option<&mut dyn FnMut(&str, &Array) -> Result<()>>,
    ) -> Result<Array> {
        if input.shape().len() != 4 || input.dim(2) != N_FREQS || input.dim(3) != 2 {
            return Err(Error::InputShape {
                actual: input.shape().to_vec(),
            });
        }
        let batch = input.dim(0);
        let frames = input.dim(1);
        let mut features = Vec::with_capacity(N_BANDS as usize);
        let mut frequency_start = 0;

        for (index, &band_width) in BAND_WIDTHS.iter().enumerate() {
            let band = input.index((.., .., frequency_start..frequency_start + band_width, ..));
            let power = band
                .square()?
                .sum_axis(-1, false)?
                .sum_axis(-1, true)?
                .add(mlx_rs::array!(MODEL_EPS))?
                .sqrt()?;
            let normalized = band.divide(power.expand_dims(-1)?.add(mlx_rs::array!(MODEL_EPS))?)?;
            let flattened = normalized.transpose_axes(&[0, 1, 3, 2])?.reshape(&[
                batch,
                frames,
                band_width * 2,
            ])?;
            let log_power = power.add(mlx_rs::array!(MODEL_EPS))?.log()?;
            let feature_input = concatenate_axis(&[flattened, log_power], -1)?;
            let feature = self.feature_extractors[index].forward(&feature_input)?;
            if let Some(callback) = trace.as_deref_mut() {
                callback(&format!("feature_extractor_layers.{index}"), &feature)?;
            }
            features.push(feature);
            frequency_start += band_width;
        }

        let residual = stack_axis(&features, 2)?;
        if let Some(callback) = trace.as_deref_mut() {
            callback("features", &residual)?;
        }
        let mut processed = residual.clone();
        for (index, layer) in self.network.iter_mut().enumerate() {
            processed = layer.forward(&processed)?;
            if let Some(callback) = trace.as_deref_mut() {
                callback(&format!("net.{index}"), &processed)?;
            }
        }
        processed = processed.add(&residual)?;
        if let Some(callback) = trace.as_deref_mut() {
            callback("processed", &processed)?;
        }

        let mut estimated_bands = Vec::with_capacity(N_BANDS as usize);
        for (index, output_layer) in self.output_layers.iter_mut().enumerate() {
            let band_features = processed.index((.., .., index as i32, ..));
            let estimated = output_layer.forward(&band_features)?;
            if let Some(callback) = trace.as_deref_mut() {
                callback(&format!("output_layers.{index}"), &estimated)?;
            }
            estimated_bands.push(estimated);
        }
        let output = concatenate_axis(&estimated_bands, 2)?;
        if let Some(callback) = trace.as_deref_mut() {
            callback("output", &output)?;
        }
        Ok(output)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bands_cover_all_frequencies() {
        assert_eq!(BAND_WIDTHS.iter().sum::<i32>(), N_FREQS);
        assert_eq!(BAND_WIDTHS.len(), N_BANDS as usize);
    }
}
